Repository SatelCreative/docker-python-base, pull requests merged in 2021-12, with the labels that each got.

#282 Add github actions
  .github/workflows/docker_image.yml
Labels: enhancement, Type: Devops

#285 Feature/multi python versions
  .github/workflows/docker_image.yml
  Dockerfile
  README.md
  docker-compose.generate_requirements.yml
  generate_requirements.sh
  requirements_3.10.txt
  requirements_3.8.txt
  requirements_3.9.txt
Labels: enhancement

#286 Decemeber tag 202112
  .github/workflows/docker_image.yml
  docker-compose.generate_requirements.yml
  requirements_3.10.txt
  requirements_3.8.txt
  requirements_3.9.txt
Labels: Type: Devops
